# Universidad de las Fuerzas Armadas ESPE

## Andrés Cosios Pineda

## Actividad No 3

## Ejercicios
## 1. Para el sistema lineal
![EJ1](EJ1.jpg)
## Encuentre los valores de x1, x2, x3, x4 utilizando sustitución progresiva. Encuentre la descomposición LU del sistema anterior. ¿Qué puede concluir?

In [42]:
import numpy as np
import math
a=np.array([[0.0,0.0,0.0,6.0],
            [0.0,0.0,6.0,3.0],
            [0.0,7.0,-2.0,4.0],
            [21.0,9.0,-3.0,5.0]])
b=np.array([12.0,-12.0,14.0,-2.0])
p=np.linalg.solve(a,b)
print ("las soluciones: X4, x3, x2, x1 son:")
print(p)
m=4
u=np.zeros([m,m])


las soluciones: X4, x3, x2, x1 son:
[-1.  0. -3.  2.]


In [43]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve
A=np.array([[0.0,0.0,0.0,6.0],
            [0.0,0.0,6.0,3.0],
            [0.0,7.0,-2.0,4.0],
            [21.0,9.0,-3.0,5.0]])
b=np.array([12.0,-12.0,14.0,-2.0])
b.shape = (4, 1)

P, L, U = lu(A)

print('La matriz L es:')
print(L)
print()
print('La matriz U es:')
print(U)


La matriz L es:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

La matriz U es:
[[21.  9. -3.  5.]
 [ 0.  7. -2.  4.]
 [ 0.  0.  6.  3.]
 [ 0.  0.  0.  6.]]


### Se puede Concluir que por medio de un código y las librerías necesarias podemos calcular sistemas lineales de forma efectiva reduciendo el tiempo, de igual manera podemos factorizar o descomponer estos sistemas en LU es decir obtener descomponer la matriz de tal manera de obtener o bien los elementos superiores ceros o los inferiores y constituye un método eficaz para resolver sistemas de ecuaciones lineales.

## 2. Resuelva las siguientes matrices usando la descomposición de Cholesky
![EJ2.jpg](EJ2.jpg)
## Analice el caso y escriba sus conclusiones.

In [44]:
import numpy as np
def cholesky(a):
    a=np.array(a, float)
    L=np.zeros_like(a)
    n,_=np.shape(a)
    for j in range (n):
        for i in range (j,n):
            if i==j:
                sumk = 0
                for k in range (j):
                    sumk += L[i,k]**2
                L[i,j]=np.sqrt(a[i,j]-sumk)
            else:
                sumk=0
                for k in range (j):
                    sumk +=L[i,k]*L[j,k]
                L[i,j]=(a[i,j]-sumk)/L[j,j]
    return L

A=[[4,6,10],
  [6,25,19],
  [10,19,62]]
L=cholesky(A)
print(L)
                

[[2. 0. 0.]
 [3. 4. 0.]
 [5. 1. 6.]]


In [45]:
import numpy as np
import pandas as pd
import math
def cholesky(a):
    a=np.array(a, float)
    L=np.zeros_like(a)
    n,_=np.shape(a)
    for j in range (n):
        for i in range (j,n):
            if i==j:
                sumk = 0
                for k in range (j):
                    sumk += L[i,k]**2
                L[i,j]=np.sqrt(a[i,j]-sumk)
            else:
                sumk=0
                for k in range (j):
                    sumk +=L[i,k]*L[j,k]
                L[i,j]=(a[i,j]-sumk)/L[j,j]
    return L

B=np.array([[4,6,10],
  [6,3,19],
  [10,19,62]])
L=cholesky(B)
print(L)

[[ 2.  0.  0.]
 [ 3. nan  0.]
 [ 5. nan nan]]


<ipython-input-45-2263242911a7>:14: RuntimeWarning: invalid value encountered in sqrt
  L[i,j]=np.sqrt(a[i,j]-sumk)


### La descomposición de Cholesky constituye un tipo de descomposición de matrices LU que consiste en la factorización en el producto de dos matrices. Es decir, igualas matrices cuadradas a una matriz con ceros por encima de la diagonal principal multiplicada por su matriz traspuesta con ceros por debajo de la diagonal principal.
### Como podemos observar en e primer caso obtenemos la matriz superior con ceros y en el segundo generamos un error ya que al cambiar un numero de la primera matriz y el programa al realizar las operaciones encuentra valores invalidos.


## 3. Utilice el método de Jacobi, Gauss-Seidel y SOR (w = 1:1) para resolver el siguiente sistema lineal con una precisión de cuatro cifras decimales.
![EJ3.jpg](EJ3.jpg)
## Compare el número de iteraciones necesario en cada algoritmo. Analice el error cometido si la solución exacta es x = (1;-1; 1;-1)^T

In [46]:
import numpy as np
A=np.array([[7,1,-1,2],
           [1,8,0,-2],
           [-1,0,4,-1],
           [2,-2,-1,6]])
b=([3,-5,4,-3])
tol = 0.0001        
error = 100000        
kmax = 100            
n = len(A)            
x = np.zeros(n)       
x1 = np.copy(x)       
k = 1                 
error1 = [0]

while k < kmax and error > tol:
    print("iteración: ",k) 
    for i in range(n):
        sumatoria = 0
        for j in range(n):
            if i != j:
                sumatoria += (A[i][j] * x[j]) # Esta es la fórmula interna de Gauss-Seidel de las sumatorias
        x[i] = (b[i]-sumatoria) / A[i][i] # Esta es la fórmula de Gauss-Seidel de las sumatorias incluyendo las sumatorias
        print("x(",i,"): ",x[i])

    error = np.linalg.norm(x-x1) # cálculo de la norma vectorial
    error1.append(error)         
    x1 = np.copy(x)              

    print("  error: ", error1[k])
    print()
    
    k += 1 

iteración:  1
x( 0 ):  0.42857142857142855
x( 1 ):  -0.6785714285714286
x( 2 ):  1.1071428571428572
x( 3 ):  -0.6845238095238096
  error:  1.5292059393648267

iteración:  2
x( 0 ):  0.8792517006802721
x( 1 ):  -0.9060374149659864
x( 2 ):  1.0486819727891157
x( 3 ):  -0.9203160430839002
  error:  0.5602402476092095

iteración:  3
x( 0 ):  0.9707644962747004
x( 1 ):  -0.9764245728053126
x( 2 ):  1.0126121132977
x( 3 ):  -0.9802943374770544
  error:  0.1350087934478646

iteración:  4
x( 0 ):  0.9928036230081602
x( 1 ):  -0.9941740372452836
x( 2 ):  1.0031273213827765
x( 3 ):  -0.9951379998540185
  error:  0.03333259944123763

iteración:  5
x( 0 ):  0.9982253369051567
x( 1 ):  -0.9985626670766492
x( 2 ):  1.0007718342627845
x( 3 ):  -0.9988006956168046
  error:  0.008223059844170936

iteración:  6
x( 0 ):  0.9995622703675775
x( 1 ):  -0.9996454577001483
x( 2 ):  1.0001903936876932
x( 3 ):  -0.9997041770746264
  error:  0.002028343783550615

iteración:  7
x( 0 ):  0.999892029362442
x( 1 ): 

In [47]:
import numpy as np
A=np.array([[7,1,-1,2],
           [1,8,0,-2],
           [-1,0,4,-1],
           [2,-2,-1,6]])
tol = 0.000001
error = 100000
kmax = 100
n = len(A)
x = np.zeros(n)
x1 = np.copy(x)
k = 1
error1=[0]
lambd = 1.4

while k < kmax and error > tol:
    print("iteración: ",k)
    for i in range(n):
        sumatoria = 0
        for j in range(n):
            if i != j:
                sumatoria += (A[i][j] * x[j])
        x[i] = (lambd*((b[i]-sumatoria) / A[i][i]))+(1-lambd)*x[i]
        print("x(",i,"): ",x[i])

    error = np.linalg.norm(x-x1)
    error1.append(error)         
    x1 = np.copy(x) 

    print("  error: ", error1[k])
    print()
    
    k += 1

iteración:  1
x( 0 ):  0.6
x( 1 ):  -0.9799999999999999
x( 2 ):  1.6099999999999999
x( 3 ):  -1.0616666666666665
  error:  2.244913386104486

iteración:  2
x( 0 ):  1.3026666666666666
x( 1 ):  -1.0825500000000001
x( 2 ):  0.84035
x( 3 ):  -1.1923527777777776
  error:  1.0553184017545556

iteración:  3
x( 0 ):  0.9404544444444445
x( 1 ):  -1.023883
x( 2 ):  0.9756955833333334
x( 3 ):  -0.9120873935185186
  error:  0.48115135181976865

iteración:  4
x( 0 ):  0.9885688962962963
x( 1 ):  -0.9576769445833335
x( 2 ):  1.036490292638889
x( 3 ):  -1.001565366720679
  error:  0.13564861451099464

iteración:  5
x( 0 ):  1.0040320356141978
x( 1 ):  -1.0181827067513889
x( 2 ):  0.9862672170571759
x( 3 ):  -1.012945049102328
  error:  0.08094387206636333

iteración:  6
x( 0 ):  1.004455190156965
x( 1 ):  -0.998037342762728
x( 2 ):  1.0025216625462527
x( 3 ):  -0.9953967744607997
  error:  0.031275608564096294

iteración:  7
x( 0 ):  0.9964884347833303
x( 1 ):  -0.9985594100432714
x( 2 ):  0.9993734

### 4. Programe un algoritmo para encontrar la norma de Frobenius para una matriz cuadrada de cualquier dimensión.

In [48]:
import numpy as np
m=np.arange(1,17).reshape(4,4)
print(m)
np.linalg.norm(m, 'fro')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


38.67815921162743

### URL codigo en GITHUB
### https://github.com/aacosios/A3_Cosios_Andres_MetodosNumericos.git